### ISSUE TITLE
Extension doesn't work (MacOS El Capitan)

### ISSUE THREAD

**Issue by jguenther-va** [sprig/org-capture-extension#8]
Nothing happens when I click the extension button (I don't get a confirmation dialog the first time I click it after installing/reinstalling the extension if that means anything).

I am able to successfully use the [links in the org-protocol documentation](http://orgmode.org/worg/org-contrib/org-protocol.html#orgheadline8) to verify my emacsclient and protocol handler setup, so I think the problem is in the extension but I'm not sure how to figure it out.

**Comment by sprig** [comment]
Can you please see if the bookmarklets work? And if so, could you send a
page for which the bookmarlets work but not the extension?

On Apr 17, 2016 08:00, "Justin Guenther" <notifications@github.com> wrote:
>
> Nothing happens when I click the extension button (I don't get a
confirmation dialog the first time I click it after installing/reinstalling
the extension if that means anything).
>
> I am able to successfully use the links in the org-protocol documentation
<http://orgmode.org/worg/org-contrib/org-protocol.html#orgheadline8> to
verify my emacsclient and protocol handler setup, so I think the problem is
in the extension but I'm not sure how to figure it out.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
<https://github.com/sprig/org-capture-extension/issues/8>

**Comment by jguenther-va** [comment]
This bookmarklet works on [the org-protocol doc page](http://orgmode.org/worg/org-contrib/org-protocol.html#orgheadline8):

```javascript
javascript:location.href='org-protocol://capture://L/'+encodeURIComponent(location.href)+
'/'+encodeURIComponent(document.title)+'/'+encodeURIComponent(window.getSelection())
```

I'm using Chrome 49.0.2623.112 if that helps. It's odd, if I click the extension button I think I can see emacsclient's icon flash in the dock but nothing seems to happen. I instrumented `org-capture` and it doesn't drop into the debugger though. Is there some sort of log I can look at to see what's going on?

**Comment by jguenther-va** [comment]
Ah, I think I figured it out. The Chrome developer tools extension shows that the link the extension tried to open was `org-protocol://capture:/...` instead of `org-protocol://capture://...`. I think #9 should fix this

**Comment by sprig** [comment]
Thanks Justin, but it does not, at least not on my machine - and a similar
proposal has been discussed before. Have you tried installing the extension
from source and verifying?

It appears that the extension does not work on pages with a hash in the
address but I still can't figure out why. If you wish, you can add a
bookmarklet for the following
```
javascript:console.log('org-protocol://capture://L/'+encodeURIComponent(location.href)+'/'+encodeURIComponent(document.title)+'/'+encodeURIComponent(window.getSelection()))
```
and see if you can spot any differences between this and my code (I cannot,
aside from said '/', which unfortunately has no effect).

**Comment by sprig** [comment]
Thanks Justin, but it does not, at least not on my machine - and a similar
proposal has been discussed before. Have you tried installing the extension
from source and verifying?

It appears that the extension does not work on pages with a hash in the
address but I still can't figure out why. If you wish, you can add a
bookmarklet for `javascript:console.log('org-protocol://capture://L/'+encodeURIComponent(location.href)+'/'+encodeURIComponent(document.title)+'/'+encodeURIComponent(window.getSelection()))`, and see if you can spot any differences between this and my code (I cannot,
aside from said '/', which unfortunately has no effect).

**Comment by sprig** [comment]
Ok, I'm not yet certain but it appears that the script is not using the api correctly to set the tab url. I'm not sure yet whether it is a changed api or just a mistake (and not yet certain this is correct).

**Comment by sprig** [comment]
@jguenther-va Could you please try installing branch `issue-8-fix` locally and let me know if it works for you? I removed the usage of chrome APIs for setting the tab location as I could not get it to work reliably.

let me know if you need instructions regarding how to locally install an extension.

**Comment by jguenther-va** [comment]
That branch fixes it, everything works now (with or without `#`). Thanks!

**Comment by jguenther-va** [comment]
If I use a `%()` in my capture template, it doesn't work if the selected text contains double-quotes. Not sure if that's a problem with org itself though, but this works well enough it's not a big deal. Feel free to close

**Comment by sprig** [comment]
That is quite odd. I tried to be very careful to make the extension handle quotes and the like. As a matter of fact, this was one of the main drivers in developing the extension (that and the nice single button you get for two different actions :-).

As an example, here is my capture template, which works fine when I select text with quotes in it.

``` elisp
("p" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
  "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?"
  :empty-lines 1)
```

If it seems like something is actually going on (rather than e.g. you had a bug in the template), would you mind starting another issue for that? please include there the simplest template you can that exhibits this behavior, along with a page and a minimal selection which triggers it?
